@baseUrl = http://localhost:8080/api
@user1 = 634e156111bf9d0adb966c1b
@user2 = 634e15ebf6bde15a7d3a6c0e
@groupSlug = test-group-1
@groupId = 634e26d2fdbce69315cedaea
@pendingId = 634e285adb584dc0ad7313d4

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzRlMTU2MTExYmY5ZDBhZGI5NjZjMWIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjY2MDgyNTA1fQ.YGIaLLvAbD_ZiHYurGm08KSIVZGUOfhJcLoZbhlW8Eg

#### USER ####
### Login
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "username": "plhuan",
  "password": "Kelkifa123"
}
### Register
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "username": "plhuan2",
  "password": "Kelkifa123",
  "email": "plhuan4552@gmail.com",
  "fullname": "Pham Long Huan2"
}

### Set Admin
PATCH  {{baseUrl}}/user/set-admin
Content-Type: application/json

{
  "userId": "{{user1}}"
}

### Check username
POST {{baseUrl}}/user/check-username
Content-Type: application/json

{
  "username": "plhuan3"
}
### Check email


#### GROUP ####
### create
POST {{baseUrl}}/group/create
Content-Type: application/json

{
  "userId": "{{user1}}",
  "name": "test group 1",
  "description": "mo ta group 1",
  "avatarImg": "https://picsum.photos/300/200"
}

### Add member 
POST {{baseUrl}}/group/add-member/{{groupSlug}}
Content-Type: application/json

{
  "userId": "{{user1}}"
}

### Get members
GET {{baseUrl}}/group/get-members/{{groupSlug}}
Content-Type: application/json

{
  "userId": "{{user1}}"
}

### Delete member
DELETE {{baseUrl}}/group/delete-member/{{groupSlug}}
Content-Type: application/json

{
  "userId": "{{user1}}",
  "deletedMemberId": "{{user2}}"
}

### Get groups
GET {{baseUrl}}/group/get-groups
Authorization: bearer {{token}}
Content-Type: application/json

{
  "userId": "{{user1}}"
}

### Delete group
DELETE {{baseUrl}}/group/delete-group/{{groupSlug}}
Content-Type: application/json

{
  "userId": "{{user1}}"
}

### Get invites
GET {{baseUrl}}/group/get-invites
Content-Type: application/json

{
  "userId": "{{user2}}"
}


### Invite member
POST {{baseUrl}}/group/invite/{{groupSlug}}
Content-Type: application/json

{
  "userId": "{{user1}}",
  "inviteMemberId": "{{user2}}"
}

### Rep Invite
POST {{baseUrl}}/group/reply-invite
Content-Type: application/json

{
  "userId": "{{user2}}",
  "isAccept": true,
  "inviteId": "634e5366fcb7a5b2432e422b"
}

#### AUTH ####

#### PENDING ####
### Get
GET {{baseUrl}}/pending/get-pending/{{groupSlug}}?month=11&year=2022
Content-Type: application/json

{
  "userId": "{{user2}}"
}
### Create
POST {{baseUrl}}/pending/create
Content-Type: application/json

{
  "content": "test pending 2",
  "date": "Wed Nov 02 2022 00:00:00 GMT+0700 (Indochina Time)",
  "money": 1000000,
  "bank": "Vietcombank",
  "groupId": "{{groupId}}",
  "userId": "{{user2}}"
}
### Update
PATCH {{baseUrl}}/pending/update
Content-Type: application/json

{
  "content": "test pending new",
  "userId": "{{user1}}",
  "pendingId": "{{pendingId}}"
}

### Delete
DELETE {{baseUrl}}/pending/delete-pending/634e285adb584dc0ad7313d4
Content-Type: application/json

{
  "userId": "{{user2}}"
}